In [8]:
import numpy as np
from numpy.ma.core import reshape

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr





array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
reshaped= arr.reshape (3,4)
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
flattened =reshaped.flatten()
flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
flattened =reshaped.flatten()
flattened[0]=19
flattened

array([19,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
raveled =reshaped.ravel()
raveled[1]=30
raveled


array([ 1, 30,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
reshaped

array([[ 1, 30,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
arr1 =np.array([1,2,3])
print(arr1)
arr2 = np.array([[2],[4],[6]])
print(arr2)

[1 2 3]
[[2]
 [4]
 [6]]
